language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: TFs1/rbcY68iqjIg3pa9TGxhuXoLYZV3ULGrLQC9AhVn+J0apBLIuGgiDh86N69P+Xy6QMpGSOKnhE1C9vHahEoJE+J3ihrRxMnvQ0tTBlTLDA2N+fK+1V9V1RgfXuwW/tSLFiI6/5vxUYto7cgYk2rjBa9JPSST3ROcrrf7gSc=
